import {buildUnsignedOutputReview,validateOutputCaseReview} from "/output-review-record.mjs?v=1";

const state={packet:null,currentId:null,caseReviews:{},reviewerId:""};
document.addEventListener("DOMContentLoaded",init);

async function api(path){const response=await fetch(path);let body;try{body=await response.json()}catch{body={error:"invalid_server_response"}}if(!response.ok)throw new Error(body.detail||body.error||`Request failed (${response.status})`);return body}

async function init(){bind();try{const summary=await api("/api/benchmark/output-review");if(!summary.blinded_to_model||summary.model_identity_included)throw new Error("The packet is not model blind.");const details=await Promise.all(summary.cases.map(item=>api(`/api/benchmark/output-review?case=${encodeURIComponent(item.case_id)}`)));state.packet={...summary,cases:details.map(item=>item.case)};renderContract();await openCase(new URLSearchParams(location.search).get("case")||state.packet.cases[0]?.case_id)}catch(error){document.getElementById("review-loading").innerHTML=`<p>Output review unavailable: ${escapeHtml(error.message)}</p>`}}

function bind(){document.getElementById("case-review-form").addEventListener("submit",saveCurrent);document.getElementById("export-review").addEventListener("click",exportReview);document.getElementById("reviewer-id").addEventListener("change",changeReviewer)}

function renderContract(){const packet=state.packet;document.getElementById("queue-title").textContent=`${packet.case_count} blinded cases`;const select=document.getElementById("reviewer-id");select.innerHTML='<option value="">Choose your identity</option>'+packet.qualified_reviewers.map(item=>`<option value="${escapeHtml(item.reviewer_id)}">${escapeHtml(item.display_name)}</option>`).join("");document.getElementById("guard-note").textContent=packet.qualified_reviewers.length?"The download is unsigned. Publish it with your own rostered Buzz key, then run the receipt validator. Nothing is submitted from this browser.":packet.pipeline.calibration.reviewer_roster_authority_state!=="signed_buzz_authority"?"Export is closed because the reviewer authority key has not been provisioned. Free-text identity and approval flags are not accepted.":"Export is closed until the configured authority signs output reviewer admissions with distinct Buzz keys.";renderQueue();renderProgress()}

function renderQueue(){document.getElementById("case-list").innerHTML=state.packet.cases.map(item=>`<button class="case-item${item.case_id===state.currentId?" active":""}${state.caseReviews[item.case_id]?" complete":""}" type="button" data-case-id="${escapeHtml(item.case_id)}"><strong>${escapeHtml(item.deal_id)}</strong><small>${escapeHtml(item.question)}</small><span class="case-meta"><span>${escapeHtml(humanize(item.task_family))}</span><span>${state.caseReviews[item.case_id]?"Saved":"Open"}</span></span></button>`).join("");document.querySelectorAll("[data-case-id]").forEach(button=>button.addEventListener("click",()=>openCase(button.dataset.caseId)))}

async function openCase(caseId){if(!caseId)return;state.currentId=caseId;const reviewCase=currentCase();history.replaceState({},"",`/benchmark/output-review?case=${encodeURIComponent(caseId)}`);document.getElementById("review-loading").hidden=true;document.getElementById("review-content").hidden=false;document.getElementById("case-breadcrumb").textContent=reviewCase.deal_id;document.getElementById("case-family").textContent=humanize(reviewCase.task_family);document.getElementById("case-question").textContent=reviewCase.question;document.getElementById("case-severity").textContent=reviewCase.severity;document.getElementById("response-hash").textContent=`sha256 ${reviewCase.response_sha256}`;document.getElementById("case-response").textContent=reviewCase.response;renderList("requested-components",reviewCase.requested_components);renderList("required-claims",reviewCase.required_claims.map(item=>item.text||item));renderList("required-citations",reviewCase.required_citations.map(item=>typeof item==="string"?item:`${item.filename||"source"} ${item.anchor||""}`));renderList("registered-calculations",reviewCase.calculations?.length?reviewCase.calculations.map(formatCalculation):["None registered"]);renderList("forbidden-claims",reviewCase.forbidden_claims.length?reviewCase.forbidden_claims:["None registered"]);renderDimensions(reviewCase);restoreCaseForm();renderQueue();document.getElementById("form-status").textContent=""}

function formatCalculation(calculation){const inputs=(calculation.inputs||[]).map(item=>`${item.name} = ${item.value} ${item.unit}`).join("; ");return `${calculation.id}: ${inputs}; ${calculation.formula} = ${calculation.expected_value} ${calculation.unit} (tolerance ${calculation.tolerance})`}

function renderDimensions(reviewCase){document.getElementById("dimension-controls").innerHTML=reviewCase.dimensions_to_review.map(dimension=>`<section class="dimension-card" data-dimension="${escapeHtml(dimension)}"><h3>${escapeHtml(humanize(dimension))}</h3><div class="segmented"><label><input type="radio" name="dimension-${escapeHtml(dimension)}" value="pass"><span>Pass</span></label><label><input type="radio" name="dimension-${escapeHtml(dimension)}" value="fail"><span>Fail</span></label></div><textarea rows="2" maxlength="2000" placeholder="Explain a failed label. Leave blank for pass."></textarea></section>`).join("")}

function restoreCaseForm(){const saved=state.caseReviews[state.currentId];document.getElementById("case-review-form").reset();if(!saved)return;for(const [dimension,value] of Object.entries(saved.dimensions)){const radio=document.querySelector(`input[name="dimension-${CSS.escape(dimension)}"][value="${value.label}"]`);if(radio)radio.checked=true;const textarea=document.querySelector(`[data-dimension="${CSS.escape(dimension)}"] textarea`);if(textarea)textarea.value=value.critique}const useful=document.querySelector(`input[name="useful"][value="${saved.useful_starting_point}"]`);if(useful)useful.checked=true;document.getElementById("deal-decision").value=saved.decision;document.getElementById("review-time").value=saved.review_time_seconds;document.getElementById("critical-corrections").value=saved.critical_corrections;document.getElementById("major-corrections").value=saved.major_corrections;document.getElementById("overall-critique").value=saved.critique}

function formValues(){const dimensions={};document.querySelectorAll("[data-dimension]").forEach(card=>{const dimension=card.dataset.dimension;dimensions[dimension]={label:card.querySelector("input:checked")?.value,critique:card.querySelector("textarea").value}});return{dimensions,useful_starting_point:document.querySelector('input[name="useful"]:checked')?.value,decision:document.getElementById("deal-decision").value,review_time_seconds:document.getElementById("review-time").value,critical_corrections:document.getElementById("critical-corrections").value,major_corrections:document.getElementById("major-corrections").value,critique:document.getElementById("overall-critique").value}}

function saveCurrent(event){event.preventDefault();const status=document.getElementById("form-status");const values=formValues();const errors=validateOutputCaseReview(currentCase(),values);if(errors.length){status.textContent=errors.join(" ");return}state.caseReviews[state.currentId]=values;status.textContent="Case saved in this browser session.";renderQueue();renderProgress();const next=state.packet.cases.find(item=>!state.caseReviews[item.case_id]);if(next)openCase(next.case_id)}

function changeReviewer(){const next=document.getElementById("reviewer-id").value;if(state.reviewerId&&next!==state.reviewerId&&Object.keys(state.caseReviews).length){state.caseReviews={};document.getElementById("form-status").textContent="Saved case decisions were cleared because the reviewer changed.";restoreCaseForm();renderQueue();renderProgress()}state.reviewerId=next;const reviewer=selectedReviewer();document.getElementById("reviewer-qualification").textContent=reviewer?.qualification||"Identity and qualification come from the domain owner managed roster.";renderProgress()}

function exportReview(){const status=document.getElementById("form-status");try{const record=buildUnsignedOutputReview({packet:state.packet,reviewer:selectedReviewer(),caseReviews:state.caseReviews});const blob=new Blob([`${JSON.stringify(record,null,2)}\n`],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`${record.review_id}.json`;anchor.click();URL.revokeObjectURL(url);status.textContent="Unsigned review downloaded. Sign it with the selected reviewer key in Buzz, then validate the signed receipt."}catch(error){status.textContent=error.message}}

function renderProgress(){const complete=Object.keys(state.caseReviews).length;const total=state.packet?.cases.length||0;document.getElementById("progress-bar").style.width=`${total?100*complete/total:0}%`;document.getElementById("progress-label").textContent=`${complete} of ${total} cases saved`;document.getElementById("export-review").disabled=!(selectedReviewer()&&complete===total&&total>0)}
function selectedReviewer(){return state.packet?.qualified_reviewers.find(item=>item.reviewer_id===document.getElementById("reviewer-id").value)}
function currentCase(){return state.packet?.cases.find(item=>item.case_id===state.currentId)}
function renderList(id,values){document.getElementById(id).innerHTML=values.map(item=>`<li>${escapeHtml(item)}</li>`).join("")}
function humanize(value){return String(value||"").replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase())}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char])}
